stages:
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.36.0
     setup:
       - script: sudo apt-get -y install libxxf86vm-dev libxrandr-dev libgl1-mesa-dev pkg-config
         condition: eq(variables['Agent.OS'], 'Linux')

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: Ralith
